services:
  web: &django
    build:
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    image: ${SERVER_NAME}
    container_name: ${SERVER_NAME}
    command: /start
    ports:
      - "${OUTBOUND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  procrastinate:
    <<: *django
    image: ${PROCRASTINATE_NAME}
    container_name: ${PROCRASTINATE_NAME}
    depends_on:
      - db
    ports: [ ]
    command: /start-procrastinate
    restart: unless-stopped
